server:
  port : 8082
spring:
  application:
    name: user_service
  cloud:
    discovery:
      enabled: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

